### ISSUE TITLE
Missing some libraries when compiling CSDK

### ISSUE THREAD

**Issue by DearHaha** [sipeed/MaixCDK#10]
Hi, I'm glad to have been exposed to such an interesting development board.

As shown in the following figure, if the "compile maixcam_lib from source code" option is not checked, the routine can be compiled normally.

![image](https://github.com/sipeed/MaixCDK/assets/174095840/da96e255-76c8-440e-9155-444f9827cdf7)
![image](https://github.com/sipeed/MaixCDK/assets/174095840/68d5d99e-c85b-44e0-9d27-82f2d409aa47)

But if this option is checked, it will cause compilation errors. 
![image](https://github.com/sipeed/MaixCDK/assets/174095840/86a03922-577d-4c20-a21f-cfb5084611ae)
![image](https://github.com/sipeed/MaixCDK/assets/174139009/a0a887d8-8883-4ed0-9406-d553b664a748)

Where should the missing lib be obtained from? Thank you.

**Comment by Neutree** [comment]
it's not open
