### ISSUE TITLE
Communication failure with an external camera

### ISSUE THREAD

**Issue by ahmed123-sys** [sipeed/MaixCDK#15]
I have a camera that works with the usb protocol. I've added this external camera to your device using a USB-C to USB-C cable, but when I run lsusb, I can't find the camera! Is there a solution to this problem?

**Comment by Neutree** [comment]
by default usb is device mode, not support external device, if you want to use usb as host mode, change `/boot/usb.dev` name to `/boot/usb.host` and reboot

**Comment by ahmed123-sys** [comment]
I changed the mode to host mode and tested two cameras. These cameras communicate successfully in nvidia jetson nano but with your hardware I can see that the second camera is not communicating because when I run lsusb I can't find it. For more information, the first camera is a webcam and the second is a TOF camera from opnous. Is there a suggestion for this problem?

**Comment by ahmed123-sys** [comment]
> by default usb is device mode, not support external device, if you want to use usb as host mode, change `/boot/usb.dev` name to `/boot/usb.host` and reboot



> I changed the mode to host mode and tested two cameras. These cameras communicate successfully in nvidia jetson nano but with your hardware I can see that the second camera is not communicating because when I run lsusb I can't find it. For more information, the first camera is a webcam and the second is a TOF camera from opnous. Is there a suggestion for this problem?

is there any update for this problem!!

**Comment by Neutree** [comment]
I tried, I can use USB camera by set `/boot/usb.dev` to `/boot/usb.host` and reboot, plug in USB camera and use `lsusb` will show up the camera, and then we can use opencv to read it

**Comment by Neutree** [comment]
I used this one 
![image](https://github.com/user-attachments/assets/fb8a3f8b-de77-464a-bcaa-f0bdf3041f6a)

**Comment by Neutree** [comment]
close this issue, if remain have problem, add new one or reopen
