### ISSUE TITLE
nn_yolov5 example fail while same model and picture in maixpy succ

### ISSUE THREAD

**Issue by taiji1985** [sipeed/MaixCDK#68]
Maixpy Succ :

```python
from maix import camera, display, image, nn, app
import sys

detector = nn.YOLOv5(model="/root/models/yolov5s.mud", dual_buff = True)

cam = camera.Camera(detector.input_width(), detector.input_height(), detector.input_format())
disp = display.Display()


while not app.need_exit():
    #img = cam.read()
    img = image.load("/root/4.jpg")
    
    img.save('/root/3.jpg')
    objs = detector.detect(img, conf_th = 0.5, iou_th = 0.45)
    for obj in objs:
        img.draw_rect(obj.x, obj.y, obj.w, obj.h, color = image.COLOR_RED)
        msg = f'{detector.labels[obj.class_id]}: {obj.score:.2f}'
        img.draw_string(obj.x, obj.y, msg, color = image.COLOR_RED)
    disp.show(img)

```
MaixCDK example fail 

path: maixcdk/examples/nn_yolov5
command :   ./nn_yolov5 /root/models/yolov5s.mud /root/4.jpg 

![image](https://github.com/user-attachments/assets/793797d3-799e-4987-b963-e1be14f49833)

4.jpg is in attached files.

[4.zip](https://github.com/user-attachments/files/18147862/4.zip)

Strangely, it's normal to use the camera directly without adding the second parameter.
cmd:  ./nn_yolov5 /root/models/yolov5s.mud

**Comment by Neutree** [comment]
![image](https://github.com/user-attachments/assets/ab67746c-e62c-4a5a-a971-c5e1c7d4ffa4)
这里代码有bug，当是图片的时候不能使用dual_buff， dual_buff 第一次detect就是会返回空的
