### ISSUE TITLE
Commented code and disabled methods in Image class

### ISSUE THREAD

**Issue by hellvesper** [sipeed/MaixCDK#71]
I've found that there is realisation of FAST/AGAST algorithms but `find_keypoints()` returns me empty arrays, so I dig into MaixCDK code and found that this code disabled:

https://github.com/sipeed/MaixCDK/blob/8ec9107d6592161066a0f811ae455be3051db20a/components/vision/src/maix_image_find_keypoints.cpp#L29
and
https://github.com/sipeed/MaixCDK/blob/8ec9107d6592161066a0f811ae455be3051db20a/components/vision/src/maix_image_find_features.cpp#L14

So I'm curious why it disabled? Is it proposed to use OpenCV realisation instead?

**Comment by Neutree** [comment]
find keypoints please use YOLOv8 or YOLO11, it's faster.
you can also try to use opencv
